"""Initial migration.

Revision ID: 034d6e36486f
Revises: 
Create Date: 2024-11-29 01:24:58.525731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034d6e36486f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('key_hex', sa.String(length=16), nullable=True),
    sa.Column('key_binary', sa.String(length=64), nullable=True),
    sa.Column('key_base64', sa.String(length=24), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('input_format', sa.String(length=10), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('round_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
